### PR TITLE
Fix handling of network drive paths in the scm panel.

### LINKED ISSUE #66: With subfolder of VOB opened on network drive, the sourcecontrol panel won't work.
Say I have the path `series\implementation` on the vob `dev`. ClearCase is configured to connect every view to a network location, e.g. X.
In my daily VS Code use I open the folder `X:\dev\series\implementation` as a workspace. The ClearCase extension detects everything and the context commands for checkin/checkout/versiontree etc with an open editor work perfect.
But in the SourceControl panel the list of checked out & view private files won't work, as the paths shown in slight grey behind the filename are not complete.

#### Example 1:
Checked out file is: `X:\dev\series\implementation\folder1\file1.cpp`
The List says:
`file1.cpp  folder1`

#### Example 2:
Checked out file is: `X:\dev\wip\dummy\folder1\file2.hpp`
The List says:
`file2.hpp  \dev\wip\dummy\folder1`

Due to this behaviour the extension / the cleartool can't resolve the filepath and won't do anything within this list except `Checkin all`.

`Rightclick -> Version Tree` on one element in the list gives the following message in the output:
> clearcase, exec error: Error: Command failed: cleartool ls "\dev\wip\dummy\folder1\file2.hpp"
> cleartool: Error: Unable to access "\dev\wip\dummy\folder1\file2.hpp": No such file or directory.

I use latest VS Code on Windows 10 and also update all extensions regularly.

### PR DESCRIPTION
**Pull request by Joinyy**
This will resolve #66. I just look for the results of the `lsco` command, that are starting with a backslash. Then I'll just add the letter of the mounted network drive (got from `workspaceFolders[0].uri.fsPath`) in front to the string. If the string is not starting with backslash, nothing will happen compared to the earlier version.

### CODE REVIEW

File: src/clearcase.ts [hunk 1]
```diff
@@ -292,16 +292,25 @@ export class ClearCase {
   public async findCheckouts(): Promise<string[]> {
     let lscoArgTmpl = this.configHandler.configuration.FindCheckoutsCommand.Value;
     let results: string[] = [];
+	let resNew: string[] = [];
```
Comment (OpenNingia) [inline src/clearcase.ts]: Can you please check the indentation of the new lines? It doesn't match with the current one.

File: src/clearcase.ts [hunk 2]
```diff
@@ -292,16 +292,25 @@ export class ClearCase {
...
+	let wsf: string[] = workspace.workspaceFolders[0].uri.fsPath;
     try {
       let cmdOpts = lscoArgTmpl.split(' ');
-      await this.runCleartoolCommand(["lsco"].concat(cmdOpts), workspace.workspaceFolders[0].uri.fsPath, (data: string[]) => {
+      await this.runCleartoolCommand(["lsco"].concat(cmdOpts), wsf, (data: string[]) => {
         results = results.concat(data);
+      });
+	  results.forEach((e) => {
```
Comment (OpenNingia) [inline src/clearcase.ts]: Also this block is not indented correctly

File: src/clearcase.ts [hunk 3]
```diff
@@ -292,16 +292,25 @@ export class ClearCase {
...
+	    if (e.startsWith("\\")) {
```
Comment (OpenNingia) [inline src/clearcase.ts]: I think this section is strictly windows-only. I would prefer to wrap this code in a function ( e.g. normalizePath or something ) so that we can provide an alternative implementation if needed.

File: src/clearcase.ts (hunk 1 above)
Comment (Joinyy) [reply src/clearcase.ts]: Yep, used tabs instead of spaces... Will update this.

File: src/clearcase.ts (hunk 2 above)
Comment (Joinyy) [reply src/clearcase.ts]: Same as above. Will update this.

File: src/clearcase.ts (hunk 3 above)
Comment (Joinyy) [reply src/clearcase.ts]: Do you think you'll need an alternative implementation for unix systems? I was thinking that the whole path alteration will only be done on windows, as unix paths won't have drive letters (=> the cleartool will always reference to workspace root or system root, which will work in both cases).
Therefore I checked for backslash to make sure, only windows paths will be altered.

Comment (OpenNingia) [reply src/clearcase.ts]: Ok, that makes sense.

File: src/clearcase.ts (hunk 1 above)
Comment (OpenNingia) [reply src/clearcase.ts]: Ok thanks, I'm going to merge this as soon as you fix the indentation.
